version: '3.0'
services:
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    volumes:
      - /data/mysql:/var/lib/mysql
    links:
      - wordpress
    environment: 
      - "MYSQL_ROOT_PASSWORD=aSv12jeas!3Nca"
      - "MYSQL_DATABASE=qincast"
      - "TZ=Asia/shanghai"
  redis:
    image: redis
    volumes: 
      - /data/redis:/data
  wordpress:
    image: wordpress:latest
    ports: 
      - "80:80"
    # volumes: 
    # - /data/wordpress :/
